### ISSUE TITLE
Question about training setting

### ISSUE THREAD

**Issue by jdg900** [Genie-Kim/PintheMemory#3]
Hello.

Thank you for sharing your nice work!

I have some questions about the training setup.

1. If I want to train the model on a single source domain (ex: GTAV), then should I run the train_GG_pinmem_DR50V3P.sh?
2. When I run the train_GG_pinmem_DR50V3P.sh, the training stops at epoch 30(about 20K iterations). However, in your paper, you described that training during 120K iterations is required. Could you explain the experimental details?

I'm looking forward to hearing from you.
Thank you!

**Comment by Genie-Kim** [comment]
Thank you for your interest in my research.
1. yes. The script train_GG_pinmem_DR50V3P.sh is for a single source domain setting.
2. For fairness, we fixed the maximum iteration of the scheduler function to 120K. And since the convergence speed tends to be slow when many source domain datasets are used, the number of early stopping iterations was adjusted for each dataset setting.
